brazilecom:
  outputs:
    dev:
      dataset: brazilecom
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/Users/User/.dbt/dsai-module-2-project-key.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: dsai-module-2-project
      threads: 3
      type: bigquery
  target: dev
liquor_sales:
  outputs:
    dev:
      dataset: iowa_liquor_sales_vdbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dsai-dbt-project
      threads: 1
      type: bigquery
  target: dev
london_bicycle:
  outputs:
    dev:
      dataset: london_bicycle_dbt
      location: EU
      method: oauth
      priority: interactive
      project: mimetic-wharf-420203
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
