
version: 2
models:
  
  - name: fact_seller_performance
    description: "Fact table containing sellers' monthly and quarterly performance, including total turnover and number of orders."
  - name: fact_best_selling_products_per_seller
    description: "Fact table containing the top 5 best-selling products for each seller based on revenue."
  - name: fact_top_selling_products
    description: "Fact table containing top-selling products and revenue generated."
  - name: fact_geolocation_sales
    description: "Fact table containing geolocation-based sales volume distribution by product."
