version: 2

models:
  - name: fact_seller_performance
    description: "Fact table for seller performance metrics"
    config:
      schema: facts
      materialized: table

  - name: fact_top_selling_products
    description: "Fact table for top-selling products and revenue generated."
    config:
      schema: facts
      materialized: table

  - name: fact_geolocation_sales
    description: "Fact table containing geolocation-based sales volume distribution by product."
    config:
      schema: facts
      materialized: table
 
  - name: fact_top_product_per_seller_geolocation
    description: "Fact table containing top selling product for each seller with geolocation."
    config:
      schema: facts
      materialized: table
