version: 2

models:
  - name: dim_customer
    description: "Dimension table for customers"
    config:
      schema: dimensions
      materialized: table
      meta:
        dagster:
          group: Star

  - name: dim_sellers
    description: "Dimension table for sellers"
    config:
      schema: dimensions
      materialized: table
      meta:
        dagster:
          group: Star

  - name: dim_products
    description: "Dimension table for products with product category name obtained from product_category table"
    config:
      schema: dimensions
      materialized: table
      meta:
        dagster:
          group: Star
  
  - name: dim_geolocation
    description: "Dimension table for geolocation"
    config:
      schema: dimensions
      materialized: table
      meta:
        dagster:
          group: Star
