brazilecom:
  target: brazilecom 
  outputs:
    threads: 1
    location: US
    priority: interactive
    brazilecom:
      type: bigquery
      method: oauth
      project: premium-node-451703-i2 # replace with Roy's project ID
      dataset: "brazilecom" # replace with Roy'ss dataset name
      retries: 2