brazilecom:
  outputs:
    dev:
      dataset: olist
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/Users/User/.dbt/dsai-module-2-project-key.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: dsai-module-2-project
      threads: 3
      type: bigquery
  target: dev
