brazilecom:
  target: dev 
  outputs:
    dev:
      threads: 1
      location: US
      type: bigquery
      project: premium-node-451703-i2 # replace with Roy's project ID
      dataset: brazilecom # replace with Roy'ss dataset name
      method: oauth
      timeout_seconds: 300
