brazilecom:
  outputs:
    dev:
      dataset: brazilecom
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/Users/User/.dbt/dsai-module-2-project-key.json
      location: asia-southeast1
      method: service-account
      project: dsai-module-2-project

      #project: premium-node-451703-i2 # replace with Roy's project ID
      #location: US
      #method: oauth
      
      priority: interactive
      threads: 3
      type: bigquery
  target: dev
